### ISSUE TITLE
Copy main IOSPE indices into EFES

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#11]

**Comment by polinayordanova** [comment]
We can start with the ones that don't need authority lists to work: 

- Greek words (where lemmatized)
- Latin words (where lemmatized)
- Lemmatized words in arbitrary language
- Fragments of text in Greek/Latin/any other language
- Numerals
- Symbols
- Abbreviations

Other indices that will require alists will take a bit more thinking about.

**Comment by ajenhl** [comment]
Are any of those particularly specific to EpiDoc? I'd like to put as much as might be also useful for TEI texts into a common core.

Also, is there any documentation about the IOSPE search, at a slightly internal way? There's a lot going on in the tei-to-solr.xsl and it would be useful to get some guidance on the what and why. Or should I just go to Paul directly?

**Comment by gabrielbodard** [comment]
I think most of those are specific to EpiDoc. Numerals and Symbols could be pretty generic, I suppose, but everything else is very specific to the EpiDoc subset of TEI. If someone wanted to index abbreviations in a non-EpiDoc TEI project, they might not find our indexes very useful. I suppose the others wouldn't hurt, but might just be ignored--abbreviations would just not work for most people.

Documentation of IOSPE search: there are a [couple pages in Confluence](https://confluence.dighum.kcl.ac.uk/display/ancdoc/IOSPE+Technical+Documentation), which may help? If Paul can't help further, I might have some idea at least of the special specs we gave them?

**Comment by ajenhl** [comment]
Great, Epidoc specific it is!

Thanks for the Confluence link - in total contrast to what Paul had said about the documentation there in general, that was actually quite helpful. My main point of confusion was the use of multiple Solr docs for a single inscription, and what this was meant to achieve. Knowing that there isn't a good reason for this means that I can do it a more usual way.

This makes it much more work adapting (I had been hoping it would largely be copy-and-paste from IOSPE to EFES here), but so it goes.

**Comment by ajenhl** [comment]
IOSPE's tei:div frequently have types, which are used in XPath expressions in the indexing. For example, for numerals, "tei:div[@type = 'edition']//tei:num".  Should I omit these predicates for EFES, or is the particular typology standard across EpiDoc?

**Comment by ajenhl** [comment]
And another question: IOSPE's indices are concerned with the line and subsection of various bits being indexed. The subsection is part of the typology mentioned in the previous question. Should line number be kept?

**Comment by gabrielbodard** [comment]
tei:div[@type]s: these are general across EpiDoc, not just to IOSPE. It is in fact illegal for there to be any tei:div with no `@type` in EpiDoc. All indices that are looking at text will *only* look for content inside `tei:div[@type='edition']`.

Subsections and line-numbers: likewise, this is EpiDoc-specific practice as well. All line references should include both the previous tei:lb that has an `@n` *and* all ancestor::divs inside the div:edition that have `@n`. (Hope that makes sense?)

**Comment by ajenhl** [comment]
Sorry, I meant the specific types, not simply having a type. IOSPE uses edition , textpart, translation, etc as type values, but if those are not standard across many or most EpiDoc projects, is it sensible to include them in EFES rather than a more generic "index whatever is in tei:body or whatever"?

**Comment by gabrielbodard** [comment]
Sorry, me who wasn't clear. :) tei:div in EpiDoc only has six legal values for `@type`: [ edition | translation | apparatus | bibliography | commentary | textpart ]. `@subtype` is unconstrained. That is EpiDoc universal. :)

**Comment by ajenhl** [comment]
Excellent. Also, I should be reading the EpiDoc documentation!

**Comment by ajenhl** [comment]
The following indices have been implemented:

* Symbols
* Abbreviations
* Fragments
* Numerals
* Words
* Lemmata
* Personal Names
