### ISSUE TITLE
Faceted browse features from IOSPE

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#12]
Copy the basic faceted browse features from IOSPE, and think about the integration of this with the indices (see #11) and the issue of authority lists (internal, external, custom, etc.)

**Comment by gabrielbodard** [comment]
With the exception of date, which I shall ticket elsewhere, initial copying of facets from IOSPE to EFES seems to be complete, so I'm closing this ticket.

**Comment by ajenhl** [comment]
Do you mean the "dating criteria" facet or the origin date slider 'facet'? The latter is done. The former I can do easily enough, since origDate/@evidence is just whitespace delimited tokens.
