### ISSUE TITLE
RDF export (Pelagios, SNAP, etc.)

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#15]

**Comment by ajenhl** [comment]
Do you know of any existing TEI->RDF converters (XSLT) for transforming into SNAP, Pelagios, etc? The only thing I could find was that Recogito is being worked on to support TEI import.

**Comment by PietroLiuzzo** [comment]
if needed I had made some Xquery and XSLT producing pelagios annotations from placeName elements in tei files for the OEDUc
https://github.com/EpiDoc/OEDUc/blob/master/oeduc-0.1/modules/rest.xql
https://github.com/EpiDoc/OEDUc/blob/master/oeduc-0.1/xslt/pelagios.xsl

**Comment by gabrielbodard** [comment]
I'm sure a few people have done this for Pelagios. There's only one, half (or less) finished bit of code for converting TEI -> SNAP that I'm aware of ([here](https://github.com/DigiClass/prosopography/tree/master/xslt)). But more important than either of these, I think--or at any case prior to them in time--would be some discussion and speccing of what features in the EpiDoc/TEI we want to export to RDF. I might try to pull together a couple of people with an interest in this question, shortly...

**Comment by gabrielbodard** [comment]
Jamie, have we left this too late to implement proper RDF export of geographical and prosopographical features in EFES 1.0? If so let's reassign this ticket to the milestone "Future Work" and leave it for now.

If not, we need to have a robust conversation/sprint to spec:

1. LAWD/Pleiades/Pelagios RDF for place information
2. SNAP RDF for person information
3. [yet-to-be-identified-ontology RDF for epigraphic information] --out of scope for EFES 1.0

**Comment by ajenhl** [comment]
I have some time to do the work, it's knowing what the mappings are that is the issue (and the piece that takes time and knowledge). There's also a little bit of front-end thought required, in terms of where should one access the RDF - a single URL to get all the RDF in the system, multiple URLs to get 'person-related' RDF (but how far to follow potential connections?), or what?

**Comment by gabrielbodard** [comment]
This ticket requires the speccing of the Pelagios, SNAP, Godot and EpOnt ontologies before it can be carried out, therefore reassigning this ticket to EFES 2.0.
