### ISSUE TITLE
Offer language versions of EpiDoc files in EFES

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#2]
(See how this is handled in Kiln and especially cf. IOSPE)

The iospe.5.*.xml files all have content in both English (@xml:lang='en') and Russian (@xml:lang='ru'). Currently, sending the file name along should return the English version; sending [filename]-ru.html should return the Russian version. I guess this will require a change in EpiDoc Example XSLT?

Maybe see if we can figure out a way to return both strings, and choose between them in the Cocoon view?

**Comment by gabrielbodard** [comment]
(Maybe this is subsumed in an existing ticket in the customization suite, in which case please feel free to close this issue. There will in any cases be differences in implementation to what I was imagining two years ago.)

**Comment by ajenhl** [comment]
Support for this (though in a slightly different fashion, with the language code being the first element in the URL path) was added in commit d79087907b82a7d36f7fe6585b4b29f0fb9b29a1.
