### ISSUE TITLE
Test suite for EFES customization

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#20]

**Comment by gabrielbodard** [comment]
@ajenhl Jamie: do we know what the solution to this ticket would look like? Is there any chance of implementing anything new for it? If no to both, close the ticket. If yes to 1. but not to 2., please describe the process accordingly, and reassign to "Future Work".

**Comment by ajenhl** [comment]
As I see it, the best avaiable approach is:

* Create an Ant task that creates a test environment and runs the test. This involves copying test files (expected output, source content files, test code) from the test directory, along with the EFES code, into a temporary directory, starting an instance of EFES, and running the (JUnit, I guess) tests.

* Create tests for individual XSLT (input document and expected output). This doesn't involve Cocoon, just running the XSLT on the input document.

* Create tests for individual (public) Cocoon map:matches. This can check actual output, though that's a fairly burdensome maintenance requirement, and/or HTTP response codes, presence of particular elements, and so forth.

**Comment by gabrielbodard** [comment]
This is an EpiDoc Stylesheets requirement, so I consider this ticket a duplicate.
