### ISSUE TITLE
Maintain technical documentation

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#21]

**Comment by ajenhl** [comment]
I should have asked this earlier - what's the specific audience for this? I have documentation in the code for people who are looking to extend or change or sometimes just use the code, while the bits I've added to the wiki or the material in the docs directory may be somewhat technical but is also aimed at people doing normal development with/in EFES.

**Comment by gabrielbodard** [comment]
The main audience for this code I think are the technical developers wishing to deploy EFES to a server, apply publication-level CSS and design, etc. Customization of basic code is under user documentation. We have discussed some enhancements, e.g. specs for server minimum requirements, etc. Further documentation may be required in later version, but I suggest reopening ticket then as needed.
