### ISSUE TITLE
Academic account of project for publication

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#25]

**Comment by gabrielbodard** [comment]
Still seeking a venue for this publication (our Digital Classicist Berlin seminar proposal having bee declined), but we should think about what sort(s) of paper(s) we want to write.

1. A technical paper for IT/tech audience?
2. A Digital Humanities paper targeted at DHQ/DCO or similar?
3. A non-technical paper targeted at epigraphists/classicists?

@ajenhl @polinayordanova any thoughts?

**Comment by ajenhl** [comment]
I think 1 and 2 should be merged - there isn't enough interesting technical stuff for a pure IT/tech audience, but some of the pieces might be of interest to the DH community. (though more in what they do/enable than in how they do it. Which, now that I say it, sounds like 2 and 3 merged. Partly this is informed by the earlier (there was on last year, I think?) publication(s) on Kiln, and the big changes in EFES are interesting from a quality of life for epigraphers perspective more than any particular new technology (though the i18n transformer is pretty cool, it's been around in Cocoon for over a decade, for example).

**Comment by gabrielbodard** [comment]
An academic paper is currently being completed by Bodard, Norrish, Stoyanova and Yordanova. Will report here/close ticket when publication is in sight.

**Comment by gabrielbodard** [comment]
Now published at:

**Gabriel Bodard & Polina Yordanova. 2020. “Publication, Testing and Visualization with EFES: A tool for all stages of the EpiDoc editing process.” _Studia Digitalia Universitatis Babeș-Bolyai_ 65.1, pp. 17–35. Available: https://doi.org/10.24193/subbdigitalia.2020.1.02**
