### ISSUE TITLE
Delete unsupported Epidoc HTML edition structure XSLT

### ISSUE THREAD

**Issue by ajenhl** [EpiDoc/EFES#29]
Once the refactoring of Epidoc XSLT in #28 is done, those htm-tpl-struct-* templates that remain should either be deleted or added to the list of XSLT needing refactoring to work with EFES.

**Comment by gabrielbodard** [comment]
Sent note to Markup warning of impending deletion of these templates.

**Comment by gabrielbodard** [comment]
This was completed long ago (but controlled via ticket in EpiDoc Sourceforge space, so neglected here. Closing.
