### ISSUE TITLE
Add lemmatised text from TEI markup to search

### ISSUE THREAD

**Issue by ajenhl** [EpiDoc/EFES#30]
Add content from tei:w/@lemma and dereferenced tei:name/@nymRef to the Solr index and allow that to be searched over.

**Comment by ajenhl** [comment]
This seems like something that is potentially useful for any TEI text, not just Epidoc, and that the indexing process should always index a lemmatised form (which, in some cases, will be the same as the non-lemmatised form). This removes the need for any indexing configuration (at this stage).

**Comment by ajenhl** [comment]
What, if anything, do we wish to do with tei:w/@lemmaRef?

**Comment by gabrielbodard** [comment]
Re `@lemmaRef`: if present, treat it like `@nymref` — i.e. try to dereference it, and fetch the headword if found.

The difference being, as far as I can see, `@nymRef` points to the xml:id of a `<nym>` element whose headword can be find in `/tei:form/tei:orth`, whereas `@lemmaRef` is not (according to the [TEI Guidelines](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/AI.html#AILCW)) normally suggested to point to a `tei:entry`, but rather to "an online lexicon", whose format we can of course not second guess.

Short answer: in the short term, either do nothing, or test for whether both `@lemmaRef` and `@nymRef` point to a TEI file, and if not, ignore them. In the medium term we'll query the Markup list for more robust suggestions.

**Comment by gabrielbodard** [comment]
I think `@lemmaRef` is not implemented, and so should be ignored for now. Anything else outstanding on this ticket? If not, close it.

**Comment by ajenhl** [comment]
Non-local @nymRef values are not supported, but supporting that (and any other 'need the external content at the time of indexing' references) would require a change to the indexing process (to operate on an aggregation of the source document and every fetched document it references).

The references to authority lists, by the way, are fine, because we just store the reference, not the referenced content (which is pulled in during display).
