### ISSUE TITLE
Should indexing be required for listing texts?

### ISSUE THREAD

**Issue by ajenhl** [EpiDoc/EFES#31]
Kiln currently lists available texts using metadata extracted directly from the TEI header, in order for users to be able to put some files in the right directory and immediately see them listed, without first indexing them in Solr.

I'd like to change that so that the information is retrieved from Solr. I think it's silly to have an entire code path that duplicates much of another one for the sole benefit of having something appear on screen one step earlier.

Any objections?

**Comment by gabrielbodard** [comment]
Are you proposing this change to Kiln core code, or just to the EFES fork?

Will there be any learning-curve implication for users—for example, is there an indexing step that needs to be mastered, or will Solr indexing at this level be automatic?

**Comment by ajenhl** [comment]
To Kiln core, but doing it in EFES first.

There's no greater learning curve than before - in order to have search, indexing must be done (typically a single link activation). This change would just require the user do that step before they could see the list of their texts. To the extent this process needs further documentation, it will be easy enough to add.

**Comment by gabrielbodard** [comment]
Okay.

Possibly unrelated question: for IOSPE, because of the size of the indices, KDL have added an offline indexing feature to prevent timeout. This is currently (a) idiosyncratic, (b) undocumented, (c) un-user-friendly. Is there any thought of implementing and improving that feature?

**Comment by ajenhl** [comment]
I wonder why IOSPE isn't using the existing ant build task that was created years ago for this exact purpose: "./build.sh solr" should do the trick. Rather than having every document's indexing XIncluded, it just crawls an automatically generated list of links to the indexing of each document.

The only thing it doesn't do (and possibly should) is remove all data from the index before starting.

**Comment by gabrielbodard** [comment]
I couldn't swear it doesn't do that—all I know is that it was explained to me as a solution external to Kiln that there was no plan to make more universal. (Although we can't have a uniquely large set of data files in IOSPE, surely?)

**Comment by ajenhl** [comment]
Fixed in d16f6e1cfc75bd80f4055d8a3d4030c8e6313818.
