### ISSUE TITLE
Link to XML from Inscription pages

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#36]
We need a link to (a) view and (b) download the original Epioc XML files from each inscription page (probably as part of the footer view of the EFES template?).

**Comment by ajenhl** [comment]
7fbed250bee4aa2bb50f8bbe5b4cd4d4fd2771aa adds a link to the full XML to the end of each inscription page. Whether the linked resource is downloaded or displayed within the browser is determined by the browser - EFES just sends the XML with an appropriate HTTP Content-Type header.

We could also link to an HTML page that includes the XML (perhaps pretty-printed, somewhat), but that seems like a cludgy approach - better to assume the user can configure their tools to do what they want.
