### ISSUE TITLE
Support images

### ISSUE THREAD

**Issue by ajenhl** [EpiDoc/EFES#37]
EpiDoc XSLT does not provide any transformation of tei:graphic into html:img. This needs to be added so that images can be displayed in EFES.

On the EpiDoc XSLT side, the transformations need to produce HTML output for the tei:graphic elements within tei:facsimile, incorporating a new parameter specifying the URL prefix for generating html:img/@src URLs.

Each tei:graphic will be transformed into an html:a linking to the full image and an html:img referencing a thumbnail image. That non-EFES EpiDoc users will have to generate such thumbnails themselves is not considered a problem.

On the EFES side the changes are:

* Passing in a suitable URL prefix (to match the existing image pipelines; ie, "/images/").
* Creating map:match sections to handle the generation of thumbnail images.

Support for using an image server will not be part of this work, except inasmuch as appropriate URLs might be generated by changing the supplied URL prefix. More significant changes to the URLs would require customisation of the EpiDoc XSLT.

**Comment by ajenhl** [comment]
Was the image support added in 1b4fe673f3386a2b0ccc0018ad2717f798e63482 accepted by participants during the second workshop? If so, I'll make that commit in the EpiDoc XSLT repository.

**Comment by gabrielbodard** [comment]
It seemed to work, yes. Does the code also allow (i.e. test for) external URLs in the `<figure>` element in Facsimile? I think people would also like that, although then we wouldn't be able to pre-process the images for thumbnails etc., of course.

**Comment by ajenhl** [comment]
I can add that in, testing for whether @url starts with "http://" or "https://" (those seem the only two cases that we should treat specially; though perhaps just checking for "://" anywhere would be better?), and not adding in the thumbnail reference or adding the prefix. Would that suffice?

**Comment by ajenhl** [comment]
I've made the changes in EFES (not committed), but am wondering about display in the Epidoc XSLT repository. Currently the edition structures default and sigidoc have apply templates rules that reach to tei:facsimile. What is the desired output (if any) of images there, in terms of the heading and such?

**Comment by gabrielbodard** [comment]
The question of how edition structure templates should handle images outside of EFES context is probably separate from this ticket, and may be worth raising for the EpiDoc Stylesheets repo more widely. Is the support for images fully documented in both user and technical documentation? That would be an essential precursor to making sure future work doesn't break EFES usage, I think.

**Comment by ajenhl** [comment]
I'm not sure how we can avoid the question of how the EpiDoc XSLT deals with it, since we're shortly switching to directly using the code from that repository, and image support relies on changes to that code. If I commit the changes I've made to the EpiDoc Stylesheets repository, it will mean that the rendering of for some of the edition structures will change if there are facsimile images present.

**Comment by ajenhl** [comment]
I could, as an interim measure, remove the template matching on tei:facsimile, and so teh default and sigidoc edition structures won't pick up the images, but iospe (which in EFES explicitly calls to tei:facsimile//tei:graphic) will. It seems that iospe is the desired default structure for EFES (please confirm) and so this might work?

**Comment by gabrielbodard** [comment]
I don't know what "desired default structure for EFES" could possibly mean, but in this case it's fair to say that IOSPE is the only edition structure template in which we're exemplifying the working display of images in EFES.

The question is, is it possible to write the template in EpiDoc Reference Stylesheets such that it works *both* in EFES, *and* when run in Oxygen completely outside the EFES context. Is the only dependency the expectation of the relationship between the HTML and the images folder in the local filesystem?

**Comment by ajenhl** [comment]
By "desired default structure for EFES", I mean the edn-structure parameter value (as set in config.xmap) that EFES ships with, and so the one for which we presumably want image support.

The image handling will work outside of the EFES context just fine. The issue is only where in an edition template the images are rendered, and with what surrounding markup - which we can avoid by my suggestion of not having the new match on tei:facsimile which creates an images section (which is what would cause the default and sigidoc templates to output image HTML in whatever place the apply-templates occurs).

**Comment by gabrielbodard** [comment]
Done.
