### ISSUE TITLE
Use i18n elements in EpiDoc XSLT

### ISSUE THREAD

**Issue by ajenhl** [EpiDoc/EFES#38]
Where static textual content is added as part of the EpiDoc XSLT transformation to HTML, this content should be wrapped in i18n:text elements with nicely specific @key values.

It needs to be checked whether common HTML renderers will be fine (ie, will ignore) these elements or not; if not, then for non-EFES EpiDoc XSLT users an additional step in the transformation, to strip out these i18n elements, may be necessary.

**Comment by gabrielbodard** [comment]
@ajenhl: Any progress on this? (Either testing or implementation.) If not, I'm raising the priority and we should aim to have this completed for release 1.0.

**Comment by ajenhl** [comment]
As far as I've been able to tell, the i18n elements don't cause any problems. I'll merge them from the version in EFES to Epidoc XSLT's master branch.

**Comment by gabrielbodard** [comment]
Perfect, thanks! This is only for the IOSPE edition structure template, right?

**Comment by ajenhl** [comment]
Actually, there is text that needs to be translated in:

* htm-teiapp.xsl
* htm-teidivapparatus.xsl
* htm-teinum.xsl

I may need to check against the other files that have changed recently.

**Comment by ajenhl** [comment]
For now I've just added the i18n markup to htm-tpl-struct-iospe.xsl. Let me know if/when it's okay for me to add them to the other files.

**Comment by gabrielbodard** [comment]
I'm not sure that teiapp or teidivapparatus really need to be translated (they shouldn't have English in them anyway, all app content is assumed to be Latin), and I'm unsure why it would it teinum either? Can we talk about this in more detail, please?

**Comment by ajenhl** [comment]
htm-teiapp.xsl contains "Other reading".

htm-teinum puts "fraction" or "number" in a span title.

htm-teidivapparatus.xsl contains "not collated".

So not a lot of text.

**Comment by gabrielbodard** [comment]
@ajenhl: was this completed, to the best of your knowledge? If not, we should probably make a ticket for the EpiDoc Sourceforge tracker, and then close this here (or postpone to 2.0, if it needs more work here).

**Comment by ajenhl** [comment]
It's done, as far as I can see, for htm-tpl-struct-iospe.xsl and htm-tpl-struct-ecg - the latter done by Tamara Kalkhitashvili. I don't know whether you want anything done for the other bits of text mentioned above; if so, I guess that should be specified in the Sourceforge tracker.
