### ISSUE TITLE
Copy or integrate EpiDoc CSS in the Kiln inscription pages

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#4]
This may involve adding the CSS as a new `<link>` to the base.xsl file, perhaps with an `<xsl:if>` saying only include this for /sample/ and /corpus/ pages, or there may be some more subtle way to include contextual css in kiln. Ask Miguel (or better, issue a "support request" through the Kiln tracker) if in doubt.

**Comment by gabrielbodard** [comment]
If the incorporation of EpiDoc CSS is already included in any of the other tickets in WP1, then please feel free to close this issue. Otherwise, add this to the milestone.

**Comment by ajenhl** [comment]
Should this CSS be used for every edition structure? I notice that there are some selectors that include an "iospe" class value. There's no issue with having that in a CSS file that is associated with the base epidoc.xml template (that is inherited by every edition structure-specific template), but it is fully possible to have a specific CSS file per edition structure if desired.

**Comment by gabrielbodard** [comment]
It might be easier not to fork the CSS, mightn't it? I mean, unless we propose to change the way this works in EpiDoc as well, better to keep it all in one place...

**Comment by ajenhl** [comment]
A fair point. I'll associate it with the base epidoc.xml template.

**Comment by ajenhl** [comment]
Fixed August 24 2017 in commit ba1675c03e66dd04f4009c88eb0dfbf5d967e601.
