### ISSUE TITLE
Add date slider to search

### ISSUE THREAD

**Issue by ajenhl** [EpiDoc/EFES#41]
I recall that a date slider on the search was mentioned before the start of the project. Is this associated with tei:msDesc/tei:history/tei:origin/tei:origDate? Specifically with @type textDate? What labels should be used for the slider?

**Comment by gabrielbodard** [comment]
Yes, tei:origDate @when OR (@notBefore and @notAfter) should be used to populate the date field (as a range) and then matched against the ranges in the slider code (I suggest half- or quarter-centuries) for overlap.

I suspect this can be copied in very large part from IOSPE, whose usage in this area is normative.

Please let me know if you need more detailed spec.

**Comment by ajenhl** [comment]
Having finally gotten the JS working (it's similar to that used by IOSPE, but IMHO cleaner and more generic), I'm now making it easier to use range queries in Kiln, because the current way it's done is not nice. The new way won't be super nice either, but at least it'll be easier for the user to set up (ie, all handled in the query XML, no XSLT code).

**Comment by ajenhl** [comment]
Closed by 2640831, ee2de5e, and d745f36.
