### ISSUE TITLE
Bibliographic references 

### ISSUE THREAD

**Issue by SigiDoc** [EpiDoc/EFES#49]
Automatically generated bibliographic references don't seem to work.

**Comment by Tamarae** [comment]
I also have this issue - in concordance there is a list of bibliography, but It seems that, it is a list of inscriptions' bibliographies, so titles are repaired for each inscription; When you click on the title you get another list:
<img width="1224" alt="Screen Shot 2020-04-06 at 08 29 50" src="https://user-images.githubusercontent.com/2108388/78558692-0eed4880-77e1-11ea-980f-3ba76b060d53.png">
<img width="1411" alt="Screen Shot 2020-04-06 at 08 30 15" src="https://user-images.githubusercontent.com/2108388/78558695-0eed4880-77e1-11ea-8815-e00fc3221449.png">

**Comment by ajenhl** [comment]
Leaving aside that it looks at first glance that the concordance_bibliography query needs to be made distinct, this looks to be functioning as designed - the bibliographic concordance (in the first image) lists the bibliographic items, that are each linked to a page giving the associated inscriptions for particular ranges within that item. Whether the separating out by reference range is appropriate in the general case is not something I'm equipped to judge, but was (I assume; my memory has discarded the details) desired at the time this functionality was implemented.

**Comment by IreneVagionakis** [comment]
This seems to have been fixed with this commit https://github.com/EpiDoc/EFES/commit/960f832576fa8a3f9706555a8e139c41dd1b6f20
