### ISSUE TITLE
entering search term fails

### ISSUE THREAD

**Issue by paregorios** [EpiDoc/EFES#5]
Clone and install EFES following instructions at http://kiln.readthedocs.org/en/latest/quickstart.html

Mac OSX 10.11.1
- Visit `/search`
- Enter an artibrary term in the `search terms` box and hit `enter`

Result:

> An error occurred
> Invalid element name. Invalid QName {fq%3Atext}
> On line 1048575, column -1 of file:///$KILN_HOME/webapps/ROOT/sitemaps/../kiln/sitemaps/../../sitemaps/../stylesheets/solr/../../kiln/stylesheets/solr/merge-parameters.xsl:

**Comment by gabrielbodard** [comment]
(I think this bug will go away as a result of the new implementation of EFES this month. Closing this issue as based on defunct code. If it recurs, we will pretty quickly notice it without this as a reminder.)
