### ISSUE TITLE
"powered by EFES"

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#58]
Publications produced with Kiln currently have a footer text which reads "Powered by Kiln". I would like to see this say "Powered by EFES" (or friendly wording!) or at least reference EFES alongside Kiln, since EFES is a much more free-standing tool than Kiln.

* What do people think we should write here?
* Where in the templates do we need to tweak this text?

**Comment by ryanfb** [comment]
Here's the two line locations in the templates:
* https://github.com/EpiDoc/EFES/blob/master/webapps/ROOT/assets/templates/base.xml#L87
* https://github.com/EpiDoc/EFES/blob/master/webapps/ROOT/assets/templates/admin/base.xml#L67

**Comment by gabrielbodard** [comment]
EpiDoc Group in October 2021 agreed that "Powered by Kiln" should be replaced by "Built on EpiDoc and delivered by EFES.” I should be able to change this (especially thanks to Ryan's note above!).

**Comment by gabrielbodard** [comment]
Done.
