### ISSUE TITLE
Rendering of images

### ISSUE THREAD

**Issue by IreneVagionakis** [EpiDoc/EFES#61]
It seems that the display of images it not working properly anymore.

With the 'sample' template in the output we have a repetition of the caption instead of a preview of the image:

![Screenshot](https://user-images.githubusercontent.com/11628725/146967762-783dceff-3587-4387-9057-9baa5fc925ff.png)

With the 'inslib' template we have no display at all of images because - I think - when we replaced all the old stylesheets with the new ones in October we went back to an older version of the 'inslib' template which does not include the handling of the <graphic> elements.

**Comment by Tamarae** [comment]
Yes,

**Comment by IreneVagionakis** [comment]
Apparently it has been fixed with [this](https://github.com/EpiDoc/EFES/commit/b870c8b54343ba8d8ff1943bd8d4730e5e0ee808) commit.
