### ISSUE TITLE
Display by default all bibliography

### ISSUE THREAD

**Issue by IreneVagionakis** [EpiDoc/EFES#62]
It would be nice to have the entire bibliography.xml file - if any - displayed by default instead of having only the concordances (so: a page with the entire bibliography, including in it the concordances).

**Comment by gabrielbodard** [comment]
In other words, we need to add a new feature to the root EFES build that adds to the main menu a page for bibliography, which renders the content of the authority file `bibliograhy.xml`. Optionally, this file can also include links to the "Concordance" pages for individual publications, as already implemented in EFES.

It is the case that we want this to be the main option; i.e. that there is no separate "concordance" page that is generated entirely from the references in inscriptions, i.e. like an index, and doesn't render any bibliography with no epigraphic references pointing to it? (I think so, but posing this here in case there's anyone who hates this option.)

**Comment by IreneVagionakis** [comment]
I have edited `webapps/ROOT/stylesheets/solr/concordance-bibliography-to-solr.xsl` in order to display in the concordance page all the bibliographic entries that are included in the authority file `bibliography.xml`: so, now the bibliographic entries that are actually referred to inside a `<div type="bibliography">` have a link that leads to the concordances, whereas the bibliographic entries that are never cited there have no links.

In any case, those who prefer that only concordances in the strict sense are displayed can obtain that by commenting out lines 89-140 of `webapps/ROOT/stylesheets/solr/concordance-bibliography-to-solr.xsl`.
