### ISSUE TITLE
Incorporate EpiDoc Example XSLT for transformation

### ISSUE THREAD

**Issue by gabrielbodard** [EpiDoc/EFES#9]

**Comment by ajenhl** [comment]
We've discussed this somewhat via email, but it's worth specifying here for public record.

The Epidoc XSLT support a number of parameters for configuring the display, and we need to decide how each of them is exposed in EFES's default rendering of Epidoc texts. There are a few questions that need to be answered for each parameter:

1. Can the publisher specify the parameter's default value for the site? (This seems a clear "yes".)
2. Can the publisher override the parameter's default value from within a call to the XSLT? (This seems a fairly clear "yes".)
3. Can a user specify the parameter's value (via the URL)?

The third question is really whether we want the default EFES installation to allow for each user to choose their own particular display of an Epidoc text, or to be restricted to the format the publisher has chosen. We needn't include any UI for selecting different parameter values if we go with the former (though that would seem an odd choice).

**Comment by emmamorlock** [comment]
Hi 
If I may join the conversation, I'd say I don't think it's reasonable to implement the third possibility. Behind these parameters there are some XSLT transformations that rely on certain data models that are specific to a project. Knowing that the publisher can choose the right parameters. Maybe it depens on parameters:
The parameter "inc-line" is a good example of a parameter that would be most appreciated by the reader to be able to choose. And that allows change without breaking anything.

**Comment by ajenhl** [comment]
If we could develop a list of which parameters are suitable for user customisation - if any - that would be very helpful/

**Comment by ajenhl** [comment]
So the parameters that makes sense in an EFES context for the user to possible set are:

* internal-app-style
* external-app-style (only one value currently supported)
* edn-structure
* edition-type
* leiden-style
* line-inc
* verse-lines

I hear a "yes" for line-inc. Do I have any statement one way or the other for the rest of them?

**Comment by gabrielbodard** [comment]
Of those seven parameters. I think clearly both [in|ex]ternal-app-style are a decision that needs to be made at the publication level, but you would want to be able to toggle or set locally the other five at the page level—indeed several of the displays we're working on have multiple values of edn-structure and verse-lines in the same page (that you switch between using CSS, for example).

Short answer: no, no, yes, yes, yes, yes, yes.

**Comment by gabrielbodard** [comment]
I haven't seen any further discussion of the question of letting users customize EpiDoc display at the browser level, and my instinct is that at the very least this would have to be something that the publisher would have the option to override/turn off. If this hasn't been implemented yet, I suggested removing that desideratum and closing this ticket. If it is very desired, it can be requested when someone is in a position to do more work on EFES in the future.

**Comment by ajenhl** [comment]
The infrastructure is in place for this in the form of internal.xmap#local-epidoc-custom-html, which was created for internal use but could be used as the basis for public use. More specifically, the simple XSLT stylesheets/epidoc/to-html.xsl contains a simple merge of request parameters with the defaults from config.xmap and calls to start-edition passing in the final parameters. It would be easy enough for someone customising EFES to make use of this to provide user's the chance to customise display via query string parameters, should they want it.

**Comment by gabrielbodard** [comment]
Okay. Is there a note to that effect in documentation anywhere? Either way, any further work is off our list this year, so I consider this ticket done.

**Comment by ajenhl** [comment]
Yes, in https://github.com/EpiDoc/EFES/wiki/EpiDoc-XSLT.
